language: python
sudo: false
branches:
  only:
    - master
python:
  - "3.6"
  - "3.5"

install:
   - pip install --upgrade setuptools
   - pip install numpy matplotlib astropy

script: py.test solsim